import { defineStrings } from '@/core/i18n/translate'

/** Tiết tấu's own strings (`drill.rhythm.*`). Shared setup and result words stay in core/i18n. */
export const S = defineStrings('rhythm', {
  title: 'Rhythm',
  what: 'Tap one measure in time',
  short: 'Rhythm',
  starter: 'tap whole, half and quarter notes in 4/4',
  'level.1': 'Whole to quarter',
  'level.1.detail': 'Whole, half, quarter in 4/4',
  'level.2': 'Eighths and rests',
  'level.2.detail': 'Adds quarter and half rests',
  'level.3': 'Dots and ties',
  'level.3.detail': 'Ties across beat 3',
  'level.4': '6/8 and triplets',
  'level.4.detail': 'Adds sixteenths',
  'setup.hint': 'Four clicks count you in, then tap every note of the measure in time.',
  'setup.level': 'Note values',
  'setup.beat': 'Beat',
  'setup.tempo': 'Tempo',
  'setup.click': 'Click during the measure',
  'setup.click.hint': 'Off: keep the beat yourself after the count-in',
  'setup.latency': 'Tap delay',
  'setup.latency.none': 'Not calibrated yet',
  'setup.latency.value': '{ms} ms taken off each tap',
  'setup.calibrate': 'Calibrate',
  'calibrate.title': 'Tap along with 8 clicks',
  'calibrate.body': 'Phones and speakers add a small delay. Tap with each click and the drill takes it off your taps.',
  'calibrate.go': 'Play the clicks',
  'calibrate.listen': 'Tap with each click',
  'calibrate.again': 'Try again',
  'calibrate.saved': 'Saved: {ms} ms',
  'calibrate.few': 'Too few taps landed near the clicks. Try again.',
  'calibrate.uneven': 'The taps were uneven. Try again, steadily.',
  'calibrate.close': 'Done',
  countIn: 'count-in',
  play: 'tap',
  pad: 'Tap',
  'pad.hint': 'touch, Space or any letter key',
  wake: 'Tap the pad to turn the sound on',
  'legend.on': 'On time',
  'legend.off': 'Early / late',
  'legend.miss': 'Missed / extra',
  'mark.on': 'on time',
  'mark.early': 'early',
  'mark.late': 'late',
  'mark.missed': 'missed',
  'mark.extra': 'extra tap',
  'verdict.right': 'In time',
  'verdict.early': 'Note {note} early by {ms} ms',
  'verdict.late': 'Note {note} late by {ms} ms',
  'verdict.missed': 'Note {note} missed',
  'verdict.extra': '{count} extra taps',
  'verdict.extra_one': '{count} extra tap',
  'result.offset': 'Avg off',
  'result.toReview': 'Measures to review',
  'result.missCount': '{count} measures',
  'result.missCount_one': '{count} measure',
}, {
  title: 'Tiết tấu',
  what: 'Gõ một ô nhịp đúng nhịp',
  short: 'Tiết tấu',
  starter: 'gõ nốt tròn, trắng, đen trong nhịp 4/4',
  'level.1': 'Tròn, trắng, đen',
  'level.1.detail': 'Ba trường độ, nhịp 4/4',
  'level.2': 'Móc đơn, dấu lặng',
  'level.2.detail': 'Thêm lặng đen, lặng trắng',
  'level.3': 'Chấm dôi, dấu nối',
  'level.3.detail': 'Nối qua phách 3',
  'level.4': '6/8 và liên ba',
  'level.4.detail': 'Thêm móc kép',
  'setup.hint': 'Bốn tiếng click đếm vào, rồi gõ từng nốt của ô nhịp cho đúng nhịp.',
  'setup.level': 'Trường độ',
  'setup.beat': 'Nhịp',
  'setup.tempo': 'Nhịp độ',
  'setup.click': 'Click trong ô nhịp',
  'setup.click.hint': 'Tắt: tự giữ nhịp sau khi đếm vào',
  'setup.latency': 'Độ trễ khi gõ',
  'setup.latency.none': 'Chưa hiệu chỉnh',
  'setup.latency.value': 'Trừ {ms} ms mỗi lần gõ',
  'setup.calibrate': 'Hiệu chỉnh',
  'calibrate.title': 'Gõ theo 8 tiếng click',
  'calibrate.body': 'Điện thoại và loa có một độ trễ nhỏ. Gõ đúng lúc từng tiếng click, bài luyện sẽ trừ độ trễ đó khỏi mỗi lần gõ.',
  'calibrate.go': 'Phát tiếng click',
  'calibrate.listen': 'Gõ theo từng tiếng click',
  'calibrate.again': 'Thử lại',
  'calibrate.saved': 'Đã lưu: {ms} ms',
  'calibrate.few': 'Chưa đủ lần gõ trúng tiếng click. Thử lại nhé.',
  'calibrate.uneven': 'Các lần gõ chưa đều. Thử lại, gõ đều tay.',
  'calibrate.close': 'Xong',
  countIn: 'đếm vào',
  play: 'gõ',
  pad: 'Gõ',
  'pad.hint': 'chạm, phím cách hoặc phím chữ',
  wake: 'Chạm vào ô Gõ để bật âm thanh',
  'legend.on': 'Đúng nhịp',
  'legend.off': 'Sớm / trễ',
  'legend.miss': 'Thiếu / thừa',
  'mark.on': 'đúng nhịp',
  'mark.early': 'sớm',
  'mark.late': 'trễ',
  'mark.missed': 'thiếu',
  'mark.extra': 'gõ thừa',
  'verdict.right': 'Đúng nhịp',
  'verdict.early': 'Nốt thứ {note} sớm {ms} ms',
  'verdict.late': 'Nốt thứ {note} trễ {ms} ms',
  'verdict.missed': 'Thiếu nốt thứ {note}',
  'verdict.extra': 'Gõ thừa {count} lần',
  'verdict.extra_one': 'Gõ thừa {count} lần',
  'result.offset': 'Lệch TB',
  'result.toReview': 'Ô nhịp cần ôn',
  'result.missCount': '{count} ô nhịp',
  'result.missCount_one': '{count} ô nhịp',
})

export const levelKey = (l: number) => S[`level.${l}` as 'level.1']
export const levelDetailKey = (l: number) => S[`level.${l}.detail` as 'level.1.detail']
