import { defineStrings } from '@/core/i18n/translate'

/** Hóa biểu's own strings (`drill.key-sig.*`). Shared setup and result words stay in core/i18n. */
export const S = defineStrings('key-sig', {
  title: 'Key signatures',
  what: 'Read a key signature, name the key',
  short: 'Key signatures',
  starter: 'name major keys with up to two sharps or flats',
  'level.1': 'Up to 2',
  'level.1.detail': 'Up to 2 sharps or flats, treble',
  'level.2': 'Up to 4',
  'level.2.detail': 'Up to 4 sharps or flats, treble',
  'level.3': 'All 15 keys',
  'level.3.detail': 'Up to 7, treble and bass',
  'level.4': 'Minor keys too',
  'level.4.detail': 'The major or its relative minor',
  'setup.level': 'Keys',
  'setup.hint': 'A key signature appears on the staff. Tap the key\'s home note on the keys.',
  'setup.answer': 'Answer keys',
  /** "Which {mode} key?": the mode word is drawn in colour, so it is passed in. */
  ask: 'Which {mode} key?',
  'mode.major': 'major',
  'mode.minor': 'minor',
  'key.major': '{key} major',
  'key.minor': '{key} minor',
  'rule.none': '{key}: no sharps or flats',
  'rule.oneFlat': '{key}: one flat',
  'rule.sharps': '{key}: {count} sharps, last sharp {last} + half step',
  'rule.sharps_one': '{key}: 1 sharp, last sharp {last} + half step',
  'rule.flats': '{key}: {count} flats, second-to-last flat {penultimate}',
  'rule.minor': '{key}: {signature} like {major}, down a minor third',
  'signature.none': 'no sharps or flats',
  'signature.sharps': '{count} sharps',
  'signature.sharps_one': '1 sharp',
  'signature.flats': '{count} flats',
  'signature.flats_one': '1 flat',
}, {
  title: 'Hóa biểu',
  what: 'Nhìn hóa biểu, gọi tên giọng',
  short: 'Hóa biểu',
  starter: 'gọi tên giọng trưởng có tới 2 dấu thăng hoặc giáng',
  'level.1': 'Tới 2 dấu',
  'level.1.detail': 'Tới 2 thăng hoặc 2 giáng, khóa Sol',
  'level.2': 'Tới 4 dấu',
  'level.2.detail': 'Tới 4 thăng hoặc 4 giáng, khóa Sol',
  'level.3': 'Cả 15 giọng',
  'level.3.detail': 'Tới 7 dấu, khóa Sol và khóa Fa',
  'level.4': 'Thêm giọng thứ',
  'level.4.detail': 'Giọng trưởng hoặc giọng thứ song song',
  'setup.level': 'Giọng',
  'setup.hint': 'Một hóa biểu hiện trên khuông nhạc. Hãy chạm nốt chủ của giọng đó trên phím.',
  'setup.answer': 'Phím trả lời',
  ask: 'Giọng {mode} nào?',
  'mode.major': 'trưởng',
  'mode.minor': 'thứ',
  'key.major': '{key} trưởng',
  'key.minor': '{key} thứ',
  'rule.none': '{key}: không dấu',
  'rule.oneFlat': '{key}: một giáng',
  'rule.sharps': '{key}: {count} thăng, thăng cuối {last} + nửa cung',
  'rule.sharps_one': '{key}: 1 thăng, thăng cuối {last} + nửa cung',
  'rule.flats': '{key}: {count} giáng, giáng áp chót {penultimate}',
  'rule.minor': '{key}: {signature} như {major}, xuống quãng 3 thứ',
  'signature.none': 'không dấu',
  'signature.sharps': '{count} thăng',
  'signature.sharps_one': '1 thăng',
  'signature.flats': '{count} giáng',
  'signature.flats_one': '1 giáng',
})

export type KeySigLevel = 1 | 2 | 3 | 4
export const levelKey = (l: number) => S[`level.${l}` as 'level.1']
export const levelDetailKey = (l: number) => S[`level.${l}.detail` as 'level.1.detail']
