import { defineStrings } from '@/core/i18n/translate'

/**
 * Quãng's own strings (`drill.intervals.*`). Shared setup and result words
 * stay in core/i18n. Interval words follow docs/theory/glossary.md: quãng,
 * thứ / trưởng / đúng / tăng / giảm.
 */
export const S = defineStrings('intervals', {
  title: 'Intervals',
  what: 'Name the interval between two notes',
  short: 'Intervals',
  starter: 'count interval sizes from 2 to 8 on white keys',
  'level.1': 'Size',
  'level.1.detail': 'Count 2 to 8, white keys',
  'level.2': 'Major, minor, perfect',
  'level.2.detail': 'White keys only',
  'level.3': 'With accidentals',
  'level.3.detail': 'Adds ♯ ♭ and the bass clef',
  'level.4': 'Augmented, diminished',
  'level.4.detail': 'The common ones',
  'setup.hint': 'Two notes on the staff: name the interval between them in one tap.',
  'setup.level': 'What to name',
  'setup.hear': 'Hear each interval',
  'setup.hear.hint': 'After each answer the two notes play, in turn or together, as written',
  'prompt.size': 'What size?',
  'prompt.name': 'What interval?',
  'row.m': 'Minor',
  'row.MP': 'Major / Perfect',
  'row.A': 'Augmented',
  'row.d': 'Diminished',
  'cell.size': '{n}',
  'cell.m': 'm{n}',
  'cell.M': 'M{n}',
  'cell.P': 'P{n}',
  'cell.A': 'A{n}',
  'cell.d': 'd{n}',
  'size.2': '2nd',
  'size.3': '3rd',
  'size.4': '4th',
  'size.5': '5th',
  'size.6': '6th',
  'size.7': '7th',
  'size.8': 'octave',
  'name.size': '{size}',
  'name.m': 'minor {size}',
  'name.M': 'major {size}',
  'name.P': 'perfect {size}',
  'name.A': 'augmented {size}',
  'name.d': 'diminished {size}',
  right: '{name} ({from} → {to})',
  missed: '{name} ({from} → {to}), you picked {pick}',
  toReview: 'Intervals to review',
}, {
  title: 'Quãng',
  what: 'Gọi tên quãng giữa hai nốt',
  short: 'Quãng',
  starter: 'đếm cỡ quãng từ 2 đến 8 trên phím trắng',
  'level.1': 'Cỡ quãng',
  'level.1.detail': 'Đếm 2 đến 8, phím trắng',
  'level.2': 'Trưởng, thứ, đúng',
  'level.2.detail': 'Chỉ phím trắng',
  'level.3': 'Có dấu hóa',
  'level.3.detail': 'Thêm ♯ ♭ và khóa Fa',
  'level.4': 'Tăng và giảm',
  'level.4.detail': 'Loại thường gặp',
  'setup.hint': 'Hai nốt trên khuông nhạc: gọi tên quãng giữa chúng bằng một lần chạm.',
  'setup.level': 'Gọi tên gì',
  'setup.hear': 'Nghe quãng sau mỗi câu',
  'setup.hear.hint': 'Hai nốt vang lên lần lượt hoặc cùng lúc, như trên khuông',
  'prompt.size': 'Quãng mấy?',
  'prompt.name': 'Quãng gì?',
  'row.m': 'Thứ',
  'row.MP': 'Trưởng / Đúng',
  'row.A': 'Tăng',
  'row.d': 'Giảm',
  'cell.size': '{n}',
  'cell.m': '{n}t',
  'cell.M': '{n}T',
  'cell.P': '{n}Đ',
  'cell.A': '{n}+',
  'cell.d': '{n}°',
  'size.2': '2',
  'size.3': '3',
  'size.4': '4',
  'size.5': '5',
  'size.6': '6',
  'size.7': '7',
  'size.8': '8',
  'name.size': 'quãng {size}',
  'name.m': 'quãng {size} thứ',
  'name.M': 'quãng {size} trưởng',
  'name.P': 'quãng {size} đúng',
  'name.A': 'quãng {size} tăng',
  'name.d': 'quãng {size} giảm',
  right: '{name} ({from} → {to})',
  missed: '{name} ({from} → {to}), bạn chọn {pick}',
  toReview: 'Quãng cần xem lại',
})

export const levelKey = (l: number) => S[`level.${l}` as 'level.1']
export const levelDetailKey = (l: number) => S[`level.${l}.detail` as 'level.1.detail']
