import { defineStrings } from '@/core/i18n/translate'

/**
 * Hợp âm's own strings (`drill.chords.*`). Shared setup and result words stay
 * in core/i18n. Theory words follow docs/theory/glossary.md (Chords).
 */
export const S = defineStrings('chords', {
  title: 'Chords',
  what: 'Name the triad on the staff',
  short: 'Chords',
  starter: 'name the seven triads of C major',
  'level.1': 'In C',
  'level.1.detail': 'White keys',
  'level.2': 'Major, minor',
  'level.2.detail': 'Any root',
  'level.3': 'Dim and aug',
  'level.3.detail': 'All four qualities',
  'level.4': 'Inversions',
  'level.4.detail': 'First and second',
  'level.5': 'Numerals · 2 ♯/♭',
  'level.5.detail': 'Major keys, up to 2',
  'level.6': 'Numerals · 4 ♯/♭',
  'level.6.detail': 'Major keys, up to 4',
  'level.7': 'Numerals · minor',
  'level.7.detail': 'Minor keys too',
  'card.5': 'Up to 2 ♯/♭',
  'card.5.detail': 'Major keys',
  'card.6': 'Up to 4 ♯/♭',
  'card.6.detail': 'Major keys',
  'card.7': 'Minor keys',
  'card.7.detail': 'With the majors',
  'setup.hint': 'A triad appears on the staff. Tap its root on the keys, then its quality.',
  'setup.hint.roman': 'A key and one of its triads. Tap the chord’s Roman numeral.',
  'setup.mode': 'Question',
  'mode.name': 'Name it',
  'mode.roman': 'Roman numeral',
  'setup.level': 'Chords',
  'setup.level.roman': 'Keys',
  'setup.listen': 'Listening',
  'setup.hear': 'Hear the chord after answering',
  'setup.hear.hint': 'On a miss, your chord first, then the right one',
  'setup.answer': 'Answer keys',
  prompt: 'Which chord?',
  'prompt.roman': 'Which numeral?',
  'key.major': '{key} major',
  'key.minor': '{key} minor',
  'step.root': '1 · Root',
  'step.quality': '2 · Quality',
  'step.numeral': 'Numeral',
  'quality.major': 'Major',
  'quality.minor': 'Minor',
  'quality.dim': 'Dim',
  'quality.aug': 'Aug',
  'quality.notAsked': 'not at this level',
  'name.major': '{root} major',
  'name.minor': '{root} minor',
  'name.dim': '{root} diminished',
  'name.aug': '{root} augmented',
  'inversion.0': 'root position',
  'inversion.1': 'first inversion',
  'inversion.2': 'second inversion',
  'result.toReview': 'Chords to review',
}, {
  title: 'Hợp âm',
  what: 'Gọi tên hợp âm ba trên khuông',
  short: 'Hợp âm',
  starter: 'gọi tên bảy hợp âm ba của giọng Do trưởng',
  'level.1': 'Giọng Do',
  'level.1.detail': 'Phím trắng',
  'level.2': 'Trưởng, thứ',
  'level.2.detail': 'Mọi nốt gốc',
  'level.3': 'Giảm, tăng',
  'level.3.detail': 'Đủ 4 tính chất',
  'level.4': 'Thế đảo',
  'level.4.detail': 'Thế đảo 1 và 2',
  'level.5': 'La Mã · 2 dấu',
  'level.5.detail': 'Giọng trưởng, đến 2 dấu',
  'level.6': 'La Mã · 4 dấu',
  'level.6.detail': 'Giọng trưởng, đến 4 dấu',
  'level.7': 'La Mã · giọng thứ',
  'level.7.detail': 'Thêm giọng thứ',
  'card.5': 'Đến 2 dấu',
  'card.5.detail': 'Giọng trưởng',
  'card.6': 'Đến 4 dấu',
  'card.6.detail': 'Giọng trưởng',
  'card.7': 'Giọng thứ',
  'card.7.detail': 'Cùng giọng trưởng',
  'setup.hint': 'Một hợp âm ba hiện trên khuông. Chạm nốt gốc trên phím, rồi chọn tính chất.',
  'setup.hint.roman': 'Một giọng và một hợp âm ba của giọng đó. Chạm bậc La Mã của hợp âm.',
  'setup.mode': 'Cách hỏi',
  'mode.name': 'Gọi tên',
  'mode.roman': 'Bậc La Mã',
  'setup.level': 'Hợp âm',
  'setup.level.roman': 'Giọng',
  'setup.listen': 'Nghe',
  'setup.hear': 'Nghe hợp âm sau khi trả lời',
  'setup.hear.hint': 'Khi sai: hợp âm bạn chọn, rồi hợp âm đúng',
  'setup.answer': 'Phím trả lời',
  prompt: 'Hợp âm gì?',
  'prompt.roman': 'Hợp âm bậc mấy?',
  'key.major': 'Giọng {key} trưởng',
  'key.minor': 'Giọng {key} thứ',
  'step.root': '1 · Nốt gốc',
  'step.quality': '2 · Tính chất',
  'step.numeral': 'Bậc',
  'quality.major': 'Trưởng',
  'quality.minor': 'Thứ',
  'quality.dim': 'Giảm',
  'quality.aug': 'Tăng',
  'quality.notAsked': 'không có ở cấp này',
  'name.major': '{root} trưởng',
  'name.minor': '{root} thứ',
  'name.dim': '{root} giảm',
  'name.aug': '{root} tăng',
  'inversion.0': 'thế gốc',
  'inversion.1': 'thế đảo 1',
  'inversion.2': 'thế đảo 2',
  'result.toReview': 'Hợp âm cần xem lại',
})

export const levelKey = (l: number) => S[`level.${l}` as 'level.1']
export const levelDetailKey = (l: number) => S[`level.${l}.detail` as 'level.1.detail']
/** A Roman level's setup card: the mode is chosen just above, so it is not repeated. */
export const cardKey = (l: number) => S[`card.${l}` as 'card.5']
export const cardDetailKey = (l: number) => S[`card.${l}.detail` as 'card.5.detail']
export const qualityKey = (q: string) => S[`quality.${q}` as 'quality.major']
export const nameKey = (q: string) => S[`name.${q}` as 'name.major']
export const inversionKey = (i: number) => S[`inversion.${i}` as 'inversion.0']
