import { defineStrings } from '@/core/i18n/translate'

/** Nghe & Đàn's own strings (`drill.hear-play.*`). Shared setup and result words stay in core/i18n. */
export const S = defineStrings('hear-play', {
  title: 'Hear & play',
  what: 'Hear a note, play it on the keys',
  short: 'Hear & play',
  starter: 'hear Do, Mi or Sol in C and find it on the keys',
  'level.1': 'Home chord',
  'level.1.detail': 'Do Mi Sol in C',
  'level.2': 'Five notes',
  'level.2.detail': 'Do to Sol, 3 keys',
  'level.3': 'Full scale',
  'level.3.detail': 'All 7 notes, 5 keys',
  'level.4': 'Chromatic',
  'level.4.detail': 'All 12 notes, 7 keys',
  'setup.level': 'Notes and keys',
  'setup.answer': 'Answer keys',
  'setup.listen': 'Listening',
  'setup.cadenceEach': 'Key before every note',
  'setup.cadenceEach.hint': "The key's chords play before each question",
  'setup.oneKey': 'Stay in one key (C)',
  'setup.oneKey.hint': 'Learn the steps in one key before keys move',
  'setup.oneKey.l1': 'This level is already in C',
  'tag.cadenceEach': 'Key every note',
  'tag.oneKey': 'One key',
  'setup.hint': 'A short chord run sets the key, then one note plays. Find it on the keys.',
  'result.aids': "Listening aids on — doesn't count toward your best",
  prompt: 'Play the note you heard',
  key: '{key} major',
  newKey: 'New key',
  replay: 'Hear again',
  right: 'That was {answer}',
  missed: 'That was {answer}, you played {chosen}',
  home: 'home note',
}, {
  title: 'Nghe & Đàn',
  what: 'Nghe một nốt, đàn lại trên phím',
  short: 'Nghe & Đàn',
  starter: 'nghe Do, Mi hoặc Sol ở giọng Do rồi tìm trên phím',
  'level.1': 'Hợp âm chủ',
  'level.1.detail': 'Do Mi Sol, giọng Do',
  'level.2': 'Năm nốt',
  'level.2.detail': 'Do đến Sol, 3 giọng',
  'level.3': 'Cả gam',
  'level.3.detail': 'Đủ 7 nốt, 5 giọng',
  'level.4': 'Nửa cung',
  'level.4.detail': 'Đủ 12 nốt, 7 giọng',
  'setup.level': 'Nốt và giọng',
  'setup.answer': 'Phím trả lời',
  'setup.listen': 'Nghe',
  'setup.cadenceEach': 'Nghe giọng trước mỗi nốt',
  'setup.cadenceEach.hint': 'Hợp âm báo giọng vang trước từng câu',
  'setup.oneKey': 'Giữ một giọng (Do)',
  'setup.oneKey.hint': 'Luyện các bậc trong một giọng trước khi đổi',
  'setup.oneKey.l1': 'Cấp này đã ở giọng Do',
  'tag.cadenceEach': 'Mỗi câu nghe giọng',
  'tag.oneKey': 'Một giọng',
  'setup.hint': 'Một chuỗi hợp âm ngắn báo giọng, rồi một nốt vang lên. Hãy tìm nốt đó trên phím.',
  'result.aids': 'Có trợ giúp nghe — không tính kỷ lục',
  prompt: 'Đàn lại nốt vừa nghe',
  key: 'Giọng {key} trưởng',
  newKey: 'Đổi giọng',
  replay: 'Nghe lại',
  right: 'Đúng là {answer}',
  missed: 'Nốt đúng là {answer}, bạn đàn {chosen}',
  home: 'nốt chủ',
})

export const levelKey = (l: number) => S[`level.${l}` as 'level.1']
export const levelDetailKey = (l: number) => S[`level.${l}.detail` as 'level.1.detail']
